### ISSUE TITLE
Make generated struct member names snake_case

### ISSUE THREAD

**Issue by stano45** [Programmierpraktikum-MVA/AsyncAPI#17]

**Comment by f-eliks** [comment]
- Irgendwie in camel_to_snake stimmt glaube ich noch was nicht ganz, weil die _ fehlen, sonst scheint es zu passen.
- vlt. nochmal auf https://docs.rs/change-case/latest/change_case/ schauen falls es umständlich ist
- Es kann sein, dass es besser ist funktionen der Template in der main hinzuzufügen statt in render_write() funktion und diese um ein Feld erweitern.
