### ISSUE TITLE
Make sure old output folder with same name is deleted when new one is generated

### ISSUE THREAD

**Issue by doepnern** [Programmierpraktikum-MVA/AsyncAPI#66]
Currently old files remain in output folder and can cause issues

**Comment by doepnern** [comment]
Vielleicht ist es tatsächlich schlau die dateien zu behalten, nur die sachen welche nicht ganze files überschreiben sondern sachen appenden wie die neuen dependencies sind halt im Moment problematisch

**Comment by f-eliks** [comment]
Ich bin mir aber nicht sicher, ob es realistisch ist, dass jemand irgendwo dateien einfügt und danach den generator laufen lässt, also warum sollte man das tun? 
Im go projekt, des letzten Jahres, haben die auch einfach den ganzen Ordner gelöscht.
Mit dem alten Weg stirbt halt die customize-ability, außer wir würden die pakete aus einer datei lesen und dann cargo adden, aber dafür müssten wir dann die cargo parsen etc. und das wäre over engineered.

**Comment by f-eliks** [comment]
Genau so könnte man aber auch sagen, dass ich erwarte, das ich einen cleanen start, habe, wenn ich ein neues Projekt generiere. 
Und ich die files erst später nach bedarf hinzufüge.
Oder wenn ich erwarte, dass Files schon nach dem generieren drin sind, dann muss ich sie vorher als templates rein gegeben haben.
